// Game metadata and registry
export const games = [
  {
    id: "clicker-rush",
    name: "Clicker Rush",
    description: "Click fast to earn points. Build combos for multipliers!",
    difficulty: "Easy",
    component: "ClickerRush",
    color: "#ff0080",
  },
  {
    id: "dodge-neon",
    name: "Dodge Neon",
    description: "Avoid neon obstacles. Speed increases over time!",
    difficulty: "Medium",
    component: "DodgeNeon",
    color: "#00ffff",
  },
  {
    id: "reaction-timer",
    name: "Reaction Timer",
    description: "Click when the screen turns green. Test your reflexes!",
    difficulty: "Easy",
    component: "ReactionTimer",
    color: "#00ff88",
  },
  {
    id: "memory-flip",
    name: "Memory Flip",
    description: "Match pairs of cards before time runs out!",
    difficulty: "Medium",
    component: "MemoryFlip",
    color: "#ff64c8",
  },
  {
    id: "endless-runner",
    name: "Endless Runner",
    description: "Switch lanes to avoid obstacles. How far can you go?",
    difficulty: "Medium",
    component: "EndlessRunner",
    color: "#00ff88",
  },
  {
    id: "color-match",
    name: "Color Match",
    description: "Match colors under time pressure. Build your streak!",
    difficulty: "Hard",
    component: "ColorMatch",
    color: "#ffff00",
  },
  {
    id: "aim-trainer",
    name: "Aim Trainer",
    description: "Click as many targets as possible before time ends!",
    difficulty: "Hard",
    component: "AimTrainer",
    color: "#ff0080",
  },
  {
    id: "tap-rhythm",
    name: "Tap Rhythm",
    description: "Follow the musical sequence. Tap the right notes!",
    difficulty: "Hard",
    component: "TapRhythm",
    color: "#ff64c8",
  },
  {
    id: "gravity-switch",
    name: "Gravity Switch",
    description: "Toggle gravity to avoid obstacles. Can you stay alive?",
    difficulty: "Hard",
    component: "GravitySwitch",
    color: "#0ea5e9",
  },
  {
    id: "ball-bounce",
    name: "Ball Bounce",
    description: "Keep the ball bouncing. Don't let it slow down!",
    difficulty: "Medium",
    component: "BallBounceSurvival",
    color: "#0ea5e9",
  },
  {
    id: "rhythm-runner",
    name: "Rhythm Runner",
    description: "A fast-paced neon rhythm platformer — timing, jumps and flow.",
    difficulty: "Varies",
    component: "RhythmRunner",
    color: "#00e6ff",
  },
  {
    id: "geo-dashers",
    name: "Geo Dashers",
    description: "A polished full-screen rhythm platformer with flight physics, vibrant obstacles, and replayable levels.",
    difficulty: "Hard",
    component: "GeoDashers",
    color: "#56eeff",
  },
];

export const getGameById = (id) => games.find((game) => game.id === id);
